In [1]:
import pandas as pd
import numpy as np

In [2]:
df = pd.read_csv('https://raw.githubusercontent.com/alexeygrigorev/mlbookcamp-code/master/chapter-02-car-price/data.csv')
len(df)

11914

In [3]:
df.head()

Make       Model  Year             Engine Fuel Type  Engine HP  \
0  BMW  1 Series M  2011  premium unleaded (required)      335.0   
1  BMW    1 Series  2011  premium unleaded (required)      300.0   
2  BMW    1 Series  2011  premium unleaded (required)      300.0   
3  BMW    1 Series  2011  premium unleaded (required)      230.0   
4  BMW    1 Series  2011  premium unleaded (required)      230.0   

   Engine Cylinders Transmission Type     Driven_Wheels  Number of Doors  \
0               6.0            MANUAL  rear wheel drive              2.0   
1               6.0            MANUAL  rear wheel drive              2.0   
2               6.0            MANUAL  rear wheel drive              2.0   
3               6.0            MANUAL  rear wheel drive              2.0   
4               6.0            MANUAL  rear wheel drive              2.0   

                         Market Category Vehicle Size Vehicle Style  \
0  Factory Tuner,Luxury,High-Performance      Compact         Coupe   
1                     Luxury,Performance      Compact   Convertible   
2                Luxury,High-Performance      Compact         Coupe   
3                     Luxury,Performance      Compact         Coupe   
4                                 Luxury      Compact   Convertible   

   highway MPG  city mpg  Popularity   MSRP  
0           26        19        3916  46135  
1           28        19        3916  40650  
2           28        20        3916  36350  
3           28        18        3916  29450  
4           28        18        3916  34500

In [4]:
df.columns = df.columns.str.replace(' ', '_').str.lower()

In [5]:
list(df.columns.values)

['make',
 'model',
 'year',
 'engine_fuel_type',
 'engine_hp',
 'engine_cylinders',
 'transmission_type',
 'driven_wheels',
 'number_of_doors',
 'market_category',
 'vehicle_size',
 'vehicle_style',
 'highway_mpg',
 'city_mpg',
 'popularity',
 'msrp']

In [6]:
features = ['make',
 'model',
 'year',
 'engine_hp',
 'engine_cylinders',
 'transmission_type',
 'vehicle_style',
 'highway_mpg',
 'city_mpg',
 'msrp']

In [7]:
df = df[features]
df.head().T

0            1         2         3            4
make                      BMW          BMW       BMW       BMW          BMW
model              1 Series M     1 Series  1 Series  1 Series     1 Series
year                     2011         2011      2011      2011         2011
engine_hp               335.0        300.0     300.0     230.0        230.0
engine_cylinders          6.0          6.0       6.0       6.0          6.0
transmission_type      MANUAL       MANUAL    MANUAL    MANUAL       MANUAL
vehicle_style           Coupe  Convertible     Coupe     Coupe  Convertible
highway_mpg                26           28        28        28           28
city_mpg                   19           19        20        18           18
msrp                    46135        40650     36350     29450        34500

In [9]:
df.isnull().count()

make                 11914
model                11914
year                 11914
engine_hp            11914
engine_cylinders     11914
transmission_type    11914
vehicle_style        11914
highway_mpg          11914
city_mpg             11914
msrp                 11914
dtype: int64

In [10]:
df.isnull().any(axis=0)

make                 False
model                False
year                 False
engine_hp             True
engine_cylinders      True
transmission_type    False
vehicle_style        False
highway_mpg          False
city_mpg             False
msrp                 False
dtype: bool

In [11]:
df.isnull().sum()

make                  0
model                 0
year                  0
engine_hp            69
engine_cylinders     30
transmission_type     0
vehicle_style         0
highway_mpg           0
city_mpg              0
msrp                  0
dtype: int64

In [12]:
df['engine_hp'] = df['engine_hp'].fillna(0)
df['engine_cylinders'] = df['engine_cylinders'].fillna(0)

In [13]:
df.isnull().sum()

make                 0
model                0
year                 0
engine_hp            0
engine_cylinders     0
transmission_type    0
vehicle_style        0
highway_mpg          0
city_mpg             0
msrp                 0
dtype: int64

In [14]:
# df.rename?
df.rename(columns={'msrp': 'price'}, inplace=True)

In [15]:
df.head().T

0            1         2         3            4
make                      BMW          BMW       BMW       BMW          BMW
model              1 Series M     1 Series  1 Series  1 Series     1 Series
year                     2011         2011      2011      2011         2011
engine_hp               335.0        300.0     300.0     230.0        230.0
engine_cylinders          6.0          6.0       6.0       6.0          6.0
transmission_type      MANUAL       MANUAL    MANUAL    MANUAL       MANUAL
vehicle_style           Coupe  Convertible     Coupe     Coupe  Convertible
highway_mpg                26           28        28        28           28
city_mpg                   19           19        20        18           18
price                   46135        40650     36350     29450        34500

# Question 1

In [16]:
df['transmission_type'].value_counts().idxmax()

'AUTOMATIC'

In [17]:
df['transmission_type'].value_counts()

AUTOMATIC           8266
MANUAL              2935
AUTOMATED_MANUAL     626
DIRECT_DRIVE          68
UNKNOWN               19
Name: transmission_type, dtype: int64

# Question 2

In [18]:
df.dtypes

make                  object
model                 object
year                   int64
engine_hp            float64
engine_cylinders     float64
transmission_type     object
vehicle_style         object
highway_mpg            int64
city_mpg               int64
price                  int64
dtype: object

In [19]:
numerical_columns = list(df.dtypes[df.dtypes != 'object'].index)
numerical_columns

['year', 'engine_hp', 'engine_cylinders', 'highway_mpg', 'city_mpg', 'price']

In [20]:
df[numerical_columns].corr()

year  engine_hp  engine_cylinders  highway_mpg  \
year              1.000000   0.338714         -0.040708     0.258240   
engine_hp         0.338714   1.000000          0.774851    -0.415707   
engine_cylinders -0.040708   0.774851          1.000000    -0.614541   
highway_mpg       0.258240  -0.415707         -0.614541     1.000000   
city_mpg          0.198171  -0.424918         -0.587306     0.886829   
price             0.227590   0.650095          0.526274    -0.160043   

                  city_mpg     price  
year              0.198171  0.227590  
engine_hp        -0.424918  0.650095  
engine_cylinders -0.587306  0.526274  
highway_mpg       0.886829 -0.160043  
city_mpg          1.000000 -0.157676  
price            -0.157676  1.000000

# Question 3

## Making binary version of price
- Now we need to turn the price variable from numeric into a binary format.
- Let's create a variable above_average which is 1 if the price is above its mean value and 0 otherwise.


In [21]:
mean_price = df['price'].mean()

In [22]:
above_average = (mean_price < df['price']).astype(int)
above_average

0        1
1        1
2        0
3        0
4        0
        ..
11909    1
11910    1
11911    1
11912    1
11913    0
Name: price, Length: 11914, dtype: int64

## Train test split

- Split your data in train/val/test sets with 60%/20%/20% distribution.
- Use Scikit-Learn for that (the train_test_split function) and set the seed to 42.
- Make sure that the target value (above_average) is not in your dataframe.


In [23]:
from sklearn.model_selection import train_test_split

In [24]:
df_train_full, df_test = train_test_split(df, test_size=0.2, random_state=42)

In [25]:
len(df_train_full), len(df_test)

(9531, 2383)

In [26]:
df_train, df_val = train_test_split(df_train_full, test_size=0.25, random_state=42)

In [27]:
len(df_train), len(df_val), len(df_test)

(7148, 2383, 2383)

In [28]:
above_average_train = (mean_price < df_train['price']).astype(int)

In [29]:
above_average_test = (mean_price < df_test['price']).astype(int)

In [30]:
above_average_val = (mean_price < df_val['price']).astype(int)

In [31]:
df_train.head().T

3972       1997         5216             2805   \
make               Mitsubishi        Kia  Lamborghini        Chevrolet   
model                Endeavor    Borrego     Gallardo         Colorado   
year                     2011       2009         2012             2016   
engine_hp               225.0      276.0        570.0            200.0   
engine_cylinders          6.0        6.0         10.0              4.0   
transmission_type   AUTOMATIC  AUTOMATIC       MANUAL        AUTOMATIC   
vehicle_style         4dr SUV    4dr SUV  Convertible  Crew Cab Pickup   
highway_mpg                19         21           20               27   
city_mpg                   15         17           12               20   
price                   33599      26245       248000            24990   

                           11369  
make                     Pontiac  
model                       Vibe  
year                        2009  
engine_hp                  158.0  
engine_cylinders             4.0  
transmission_type      AUTOMATIC  
vehicle_style      4dr Hatchback  
highway_mpg                   26  
city_mpg                      20  
price                      20475

In [32]:
df_train.reset_index(drop=True)

make     model  year  engine_hp  engine_cylinders  \
0      Mitsubishi  Endeavor  2011      225.0               6.0   
1             Kia   Borrego  2009      276.0               6.0   
2     Lamborghini  Gallardo  2012      570.0              10.0   
3       Chevrolet  Colorado  2016      200.0               4.0   
4         Pontiac      Vibe  2009      158.0               4.0   
...           ...       ...   ...        ...               ...   
7143       Toyota    Sienna  2016      266.0               6.0   
7144    Chevrolet       HHR  2009      260.0               4.0   
7145      Hyundai  Veracruz  2012      260.0               6.0   
7146   Mitsubishi      Expo  1993      136.0               4.0   
7147         Ford    Taurus  2015      365.0               6.0   

     transmission_type      vehicle_style  highway_mpg  city_mpg   price  
0            AUTOMATIC            4dr SUV           19        15   33599  
1            AUTOMATIC            4dr SUV           21        17   26245  
2               MANUAL        Convertible           20        12  248000  
3            AUTOMATIC    Crew Cab Pickup           27        20   24990  
4            AUTOMATIC      4dr Hatchback           26        20   20475  
...                ...                ...          ...       ...     ...  
7143         AUTOMATIC  Passenger Minivan           25        18   37655  
7144            MANUAL              Wagon           29        21   25135  
7145         AUTOMATIC            4dr SUV           22        17   28345  
7146            MANUAL      2dr Hatchback           26        19    2000  
7147         AUTOMATIC              Sedan           25        17   40220  

[7148 rows x 10 columns]

In [33]:
df_train = df_train.reset_index(drop=True)
df_test = df_test.reset_index(drop=True)
df_val = df_val.reset_index(drop=True)

In [34]:
df_train_full = df_train_full.reset_index(drop=True)

In [35]:
above_average_train_full = (mean_price < df_train_full['price']).astype(int)

In [36]:
df_train_full.isnull().sum()

make                 0
model                0
year                 0
engine_hp            0
engine_cylinders     0
transmission_type    0
vehicle_style        0
highway_mpg          0
city_mpg             0
price                0
dtype: int64

In [37]:
above_average_train_full.value_counts()

0    6893
1    2638
Name: price, dtype: int64

In [38]:
above_average_train_full.value_counts(normalize=True)

0    0.723219
1    0.276781
Name: price, dtype: float64

In [39]:
global_above_average = above_average_train_full.mean()
global_above_average

0.2767810303221068

In [40]:
df_train_full.dtypes

make                  object
model                 object
year                   int64
engine_hp            float64
engine_cylinders     float64
transmission_type     object
vehicle_style         object
highway_mpg            int64
city_mpg               int64
price                  int64
dtype: object

In [41]:
numerical_columns

['year', 'engine_hp', 'engine_cylinders', 'highway_mpg', 'city_mpg', 'price']

In [42]:
categorical_columns = list(df.dtypes[df.dtypes == 'object'].index)
categorical_columns

['make', 'model', 'transmission_type', 'vehicle_style']

## Mutual Info

- Calculate the mutual information score between above_average and other categorical variables in our dataset. Use the training set only.
- Round the scores to 2 decimals using round(score, 2).

In [43]:
from sklearn.metrics import mutual_info_score

mutual_info_score(above_average_train, df_train.price)

0.5896950056764694

In [44]:
mutual_info_score(above_average_train, df_train.year)

0.07154435155401667

In [45]:
def mutual_info_churn_score(series):
    return mutual_info_score(series, above_average_train)

In [46]:
mi = df_train[categorical_columns].apply(mutual_info_churn_score)
mi.sort_values(ascending=False).round(2)

model                0.46
make                 0.24
vehicle_style        0.08
transmission_type    0.02
dtype: float64

# Question 4

- Now let's train a logistic regression.
- Remember that we have several categorical variables in the dataset. Include them using one-hot encoding.
- Fit the model on the training dataset.
  - To make sure the results are reproducible across different versions of Scikit-Learn, fit the model with these parameters:
  - model = LogisticRegression(solver='liblinear', C=10, max_iter=1000, random_state=42)
- Calculate the accuracy on the validation dataset and round it to 2 decimal digits.



In [47]:
from sklearn.feature_extraction import DictVectorizer

In [48]:
dv = DictVectorizer(sparse=False)

In [49]:
train_dict = df_train[categorical_columns + numerical_columns].to_dict(orient='records')

In [50]:
train_dict[0]

{'make': 'Mitsubishi',
 'model': 'Endeavor',
 'transmission_type': 'AUTOMATIC',
 'vehicle_style': '4dr SUV',
 'year': 2011,
 'engine_hp': 225.0,
 'engine_cylinders': 6.0,
 'highway_mpg': 19,
 'city_mpg': 15,
 'price': 33599}

In [51]:
dv = DictVectorizer(sparse=False)
dv.fit(train_dict)

DictVectorizer(sparse=False)

In [52]:
dv.get_feature_names_out()

array(['city_mpg', 'engine_cylinders', 'engine_hp', 'highway_mpg',
       'make=Acura', 'make=Alfa Romeo', 'make=Aston Martin', 'make=Audi',
       'make=BMW', 'make=Bentley', 'make=Bugatti', 'make=Buick',
       'make=Cadillac', 'make=Chevrolet', 'make=Chrysler', 'make=Dodge',
       'make=FIAT', 'make=Ferrari', 'make=Ford', 'make=GMC',
       'make=Genesis', 'make=HUMMER', 'make=Honda', 'make=Hyundai',
       'make=Infiniti', 'make=Kia', 'make=Lamborghini', 'make=Land Rover',
       'make=Lexus', 'make=Lincoln', 'make=Lotus', 'make=Maserati',
       'make=Maybach', 'make=Mazda', 'make=McLaren', 'make=Mercedes-Benz',
       'make=Mitsubishi', 'make=Nissan', 'make=Oldsmobile',
       'make=Plymouth', 'make=Pontiac', 'make=Porsche',
       'make=Rolls-Royce', 'make=Saab', 'make=Scion', 'make=Spyker',
       'make=Subaru', 'make=Suzuki', 'make=Tesla', 'make=Toyota',
       'make=Volkswagen', 'make=Volvo', 'model=1 Series', 'model=100',
       'model=124 Spider', 'model=190-Class', 'model

In [53]:
dv.transform(train_dict[:5])[0]

array([1.5000e+01, 6.0000e+00, 2.2500e+02, 1.9000e+01, 0.0000e+00,
       0.0000e+00, 0.0000e+00, 0.0000e+00, 0.0000e+00, 0.0000e+00,
       0.0000e+00, 0.0000e+00, 0.0000e+00, 0.0000e+00, 0.0000e+00,
       0.0000e+00, 0.0000e+00, 0.0000e+00, 0.0000e+00, 0.0000e+00,
       0.0000e+00, 0.0000e+00, 0.0000e+00, 0.0000e+00, 0.0000e+00,
       0.0000e+00, 0.0000e+00, 0.0000e+00, 0.0000e+00, 0.0000e+00,
       0.0000e+00, 0.0000e+00, 0.0000e+00, 0.0000e+00, 0.0000e+00,
       0.0000e+00, 1.0000e+00, 0.0000e+00, 0.0000e+00, 0.0000e+00,
       0.0000e+00, 0.0000e+00, 0.0000e+00, 0.0000e+00, 0.0000e+00,
       0.0000e+00, 0.0000e+00, 0.0000e+00, 0.0000e+00, 0.0000e+00,
       0.0000e+00, 0.0000e+00, 0.0000e+00, 0.0000e+00, 0.0000e+00,
       0.0000e+00, 0.0000e+00, 0.0000e+00, 0.0000e+00, 0.0000e+00,
       0.0000e+00, 0.0000e+00, 0.0000e+00, 0.0000e+00, 0.0000e+00,
       0.0000e+00, 0.0000e+00, 0.0000e+00, 0.0000e+00, 0.0000e+00,
       0.0000e+00, 0.0000e+00, 0.0000e+00, 0.0000e+00, 0.0000e

In [54]:
list(dv.transform(train_dict[:5])[0])

[15.0,
 6.0,
 225.0,
 19.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 1.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,


In [55]:
X_train = dv.fit_transform(train_dict)

In [56]:
X_train.shape

(7148, 944)

In [57]:
val_dicts = df_val[categorical_columns + numerical_columns].to_dict(orient='records')

In [58]:
X_val = dv.transform(val_dicts)

In [59]:
from sklearn.linear_model import LogisticRegression

In [60]:
model = LogisticRegression(solver='liblinear', C=10, max_iter=1000, random_state=42)

In [61]:
y_train = above_average_train

In [62]:
model.fit(X_train, y_train)

LogisticRegression(C=10, max_iter=1000, random_state=42, solver='liblinear')

In [63]:
model.coef_

array([[-4.11929852e-03, -7.70422528e-04, -2.34840078e-03,
        -3.65829166e-03, -4.36374719e-04,  8.17137188e-09,
         5.67310553e-09, -5.68823880e-06,  2.77909911e-04,
         2.70534500e-09, -3.14938692e-10,  2.79201788e-05,
        -9.77845187e-05, -1.95218229e-04,  1.49215080e-04,
        -1.03549690e-04, -4.88850074e-08,  2.18875832e-09,
         1.35618983e-04,  2.90223708e-04,  1.12189903e-05,
        -5.71867022e-06, -1.01015411e-05,  1.15234778e-05,
        -3.75067171e-05, -1.58301636e-04,  1.76431047e-09,
         4.92020025e-05, -1.76676171e-04,  1.31665603e-06,
         3.74616179e-08,  7.89761481e-09,  2.73301839e-10,
         1.45306541e-06,  1.51128889e-10,  4.67039667e-05,
        -9.62089944e-07,  4.67932944e-04, -4.83995323e-07,
         4.57113433e-08, -4.31153439e-07,  7.18548030e-08,
         1.00003017e-09, -2.89431845e-04, -3.82885844e-08,
         2.18399485e-10, -5.14585175e-05, -2.19680573e-07,
         4.19821986e-09,  3.42522758e-04, -4.26245834e-0

In [64]:
model.coef_[0].round(3) # weights

array([-0.004, -0.001, -0.002, -0.004, -0.   ,  0.   ,  0.   , -0.   ,
        0.   ,  0.   , -0.   ,  0.   , -0.   , -0.   ,  0.   , -0.   ,
       -0.   ,  0.   ,  0.   ,  0.   ,  0.   , -0.   , -0.   ,  0.   ,
       -0.   , -0.   ,  0.   ,  0.   , -0.   ,  0.   ,  0.   ,  0.   ,
        0.   ,  0.   ,  0.   ,  0.   , -0.   ,  0.   , -0.   ,  0.   ,
       -0.   ,  0.   ,  0.   , -0.   , -0.   ,  0.   , -0.   , -0.   ,
        0.   ,  0.   , -0.   , -0.   ,  0.   , -0.   , -0.   , -0.   ,
       -0.   , -0.   , -0.   , -0.   , -0.   , -0.   , -0.   ,  0.   ,
        0.   ,  0.   , -0.   , -0.   , -0.   , -0.   , -0.   , -0.   ,
        0.   ,  0.   ,  0.   ,  0.   ,  0.   , -0.   , -0.   ,  0.   ,
        0.   ,  0.   ,  0.   , -0.   ,  0.   ,  0.   , -0.   , -0.   ,
       -0.   , -0.   , -0.   ,  0.   , -0.   ,  0.   ,  0.   ,  0.   ,
        0.   , -0.   ,  0.   ,  0.   , -0.   , -0.   ,  0.   ,  0.   ,
       -0.   ,  0.   , -0.   , -0.   , -0.   , -0.   , -0.   , -0.   ,
      

In [65]:
model.intercept_[0].round(3)

-0.0

In [66]:
model.predict_proba(X_train)

array([[1.00000000e+000, 4.76022445e-028],
       [1.00000000e+000, 4.44560929e-057],
       [0.00000000e+000, 1.00000000e+000],
       ...,
       [1.00000000e+000, 5.52372340e-049],
       [1.00000000e+000, 1.03847986e-151],
       [9.73809322e-001, 2.61906781e-002]])

In [67]:
y_pred = model.predict_proba(X_val)[:, 1]
y_pred

array([6.87097466e-48, 1.00000000e+00, 5.01382436e-81, ...,
       1.97278901e-73, 1.00000000e+00, 1.00000000e+00])

In [68]:
churn_decision = (y_pred >=0.5)
churn_decision

array([False,  True, False, ..., False,  True,  True])

In [69]:
y_val = above_average_val

In [70]:
churn_decision.astype(int)

array([0, 1, 0, ..., 0, 1, 1])

In [71]:
accuracy = (y_val == churn_decision).mean()
accuracy

0.9995803608896349

In [72]:
y_pred = model.predict(X_val)
print(f"y_pred.shape: {y_pred.shape} type: {type(y_pred)}")
accuracy = (y_val == y_pred).mean()
print(f"accuracy: {accuracy}")

y_pred.shape: (2383,) type: <class 'numpy.ndarray'>
accuracy: 0.9995803608896349


In [73]:
categorical_columns

['make', 'model', 'transmission_type', 'vehicle_style']

In [83]:
#Import math Library
import math 

for c in categorical_columns:
    categ = categorical_columns.copy()
    categ.remove(c)
    print(categ)
    train_dict = df_train[categ + numerical_columns].to_dict(orient='records')
    dv_new = DictVectorizer(sparse=False)
    X_train_new = dv_new.fit_transform(train_dict)
    print(f"X_train_new.shape: {X_train_new.shape}")
    val_dicts = df_val[categ + numerical_columns].to_dict(orient='records')
    X_val_new = dv_new.transform(val_dicts)
    model = LogisticRegression(solver='liblinear', C=10, max_iter=1000, random_state=42)
    y_train = above_average_train
    model.fit(X_train_new, y_train)
    y_pred_new = model.predict_proba(X_val_new)[:, 1]
    churn_decision_new = (y_pred_new >=0.5)
    y_val = above_average_val
    acc_new = (y_val == churn_decision_new).mean()
    print(f"Accuracy: {acc_new} diff: {math.fabs(accuracy-acc_new)}")

['model', 'transmission_type', 'vehicle_style']
X_train_new.shape: (7148, 896)
Accuracy: 0.9995803608896349 diff: 0.0
['make', 'transmission_type', 'vehicle_style']
X_train_new.shape: (7148, 75)
Accuracy: 0.9995803608896349 diff: 0.0
['make', 'model', 'vehicle_style']
X_train_new.shape: (7148, 939)
Accuracy: 0.9995803608896349 diff: 0.0
['make', 'model', 'transmission_type']
X_train_new.shape: (7148, 928)
Accuracy: 0.9995803608896349 diff: 0.0


# Question 6

In [84]:
from sklearn.linear_model import Ridge
from sklearn.metrics import mean_squared_error

In [85]:
log_y_train = np.log1p(df_train['price'])
log_y_test = np.log1p(df_test['price'])
log_y_val = np.log1p(df_val['price'])

In [86]:
len(log_y_train)

7148

In [87]:
np.log1p(np.expm1(10))

10.0

In [88]:
Ridge?

In [89]:
for alpha in [0, 0.01, 0.1, 1, 10]:
    print(f"processing for alpha: {alpha}")
    model = Ridge(alpha=alpha, solver='sag', random_state=42, max_iter=200)
    model.fit(X_train, log_y_train)
    y_pred = model.predict(X_val)
    y_val = df_val['price']
    print(f"y_pred.shape: {y_pred.shape} type: {type(y_pred)}, y_val.shape: {y_val.shape} type: {type(y_val)}")
    accuracy = mean_squared_error(y_val, y_pred, squared=False)
    print(f"Alpha: {alpha}, Accuracy: {accuracy}")

processing for alpha: 0


/home/pinku/miniconda3/lib/python3.8/site-packages/sklearn/linear_model/_sag.py:350: ConvergenceWarning: The max_iter was reached which means the coef_ did not converge
  warnings.warn(


y_pred.shape: (2383,) type: <class 'numpy.ndarray'>, y_val.shape: (2383,) type: <class 'pandas.core.series.Series'>
Alpha: 0, Accuracy: 82408.54275439013
processing for alpha: 0.01


/home/pinku/miniconda3/lib/python3.8/site-packages/sklearn/linear_model/_sag.py:350: ConvergenceWarning: The max_iter was reached which means the coef_ did not converge
  warnings.warn(


y_pred.shape: (2383,) type: <class 'numpy.ndarray'>, y_val.shape: (2383,) type: <class 'pandas.core.series.Series'>
Alpha: 0.01, Accuracy: 82408.54275439013
processing for alpha: 0.1


/home/pinku/miniconda3/lib/python3.8/site-packages/sklearn/linear_model/_sag.py:350: ConvergenceWarning: The max_iter was reached which means the coef_ did not converge
  warnings.warn(


y_pred.shape: (2383,) type: <class 'numpy.ndarray'>, y_val.shape: (2383,) type: <class 'pandas.core.series.Series'>
Alpha: 0.1, Accuracy: 82408.54275439013
processing for alpha: 1


/home/pinku/miniconda3/lib/python3.8/site-packages/sklearn/linear_model/_sag.py:350: ConvergenceWarning: The max_iter was reached which means the coef_ did not converge
  warnings.warn(


y_pred.shape: (2383,) type: <class 'numpy.ndarray'>, y_val.shape: (2383,) type: <class 'pandas.core.series.Series'>
Alpha: 1, Accuracy: 82408.54275439013
processing for alpha: 10
y_pred.shape: (2383,) type: <class 'numpy.ndarray'>, y_val.shape: (2383,) type: <class 'pandas.core.series.Series'>
Alpha: 10, Accuracy: 82408.54275439015


/home/pinku/miniconda3/lib/python3.8/site-packages/sklearn/linear_model/_sag.py:350: ConvergenceWarning: The max_iter was reached which means the coef_ did not converge
  warnings.warn(
